# Run Component Governance to detect open source components

trigger:
  - main

pool:
  vmImage: 'windows-latest'

steps:
  - task: npmAuthenticate@0
    inputs:
      workingFile: .azure-devops/.npmrc

  - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
    displayName: 'CG Component Detection'

  - task: securedevelopmentteam.vss-secure-development-tools.build-task-policheck.PoliCheck@1
    displayName: Run PoliCheck on source
    inputs:
      targetArgument: $(Build.SourcesDirectory)
    continueOnError: false
